#!/usr/bin/env bash

## Description: Runs PHPUnit tests with code coverage enabled and writes the coverage.xml report to coverage/coverage.xml.
## usage: ddev symfony test_coverage

echo "run coverage tests"

php vendor/bin/phpunit --coverage-clover public/coverage/coverage.xml
